//Made by Daniel Sabanov
//IMPORTANT! This is the driver method for the 2nd milestone, not the team manager for milestone 3.

package nflteammanager;


public class NflTeamManager {

    public static void main(String[] args) {
        driver();
    }
    public static void driver(){
        NFLPlayer player1 = new NFLPlayer();
        //creates a new instance of an NFLPlayer through the no argument constructor.
        
        NFLPlayer player2 = new NFLPlayer(1, 2, 3, 4, 5, 6, "Bob", "Smith", "QB", "Cardinals");
        //creates a new instance of an NFLPlayer through the argumented constructor.
       
        System.out.println("player1 autogenerated parameters");
        //Tells for which instance the following output is intended.
        
        System.out.println(player1.toString());
        //Shows the values generated by the constructor with no parameters.
        
        System.out.println("player2 generated parameters");
        //Tells for which instance the following output is intended.
        
        System.out.println(player2.toString());
        //Shows the instance generated by the constructor, as well as tests the toString method.
        
        System.out.println("computational properties");
        //Prints what is going to be displayed in the console next
        
        System.out.println(player2.getPlayerFullName());
        System.out.println(player2.getPlayerOverallDistance());
        //Prints out the output of the getter methods that add variables.
        
        player2.setPlayerHeight(0);
        player2.setPlayerPassDistance(0);
        player2.setPlayerRunDistance(0);
        player2.setPlayerSpeed(0);
        player2.setPlayerWeight(0);
        player2.setPlayerAge(0);
        //Sets all the integer properties to 0 for player2.
        
        System.out.println("The following should output six zeros");
        //Prints out what should be the correct output.
        
        System.out.println(player2.getPlayerHeight());
        System.out.println(player2.getPlayerPassDistance());
        System.out.println(player2.getPlayerRunDistance());
        System.out.println(player2.getPlayerSpeed());
        System.out.println(player2.getPlayerWeight());
        System.out.println(player2.getPlayerAge());
        //Prints all the integers that just have been set to 0 to make sure the 
        //setters and the getters work as intended.
        
        System.out.println(player1.toString());
        //prints the values that are stored in the player1 instance to make sure 
        //that the values did not change after calling on player2 instance setter methods.
        
        player2.setPlayerCurrentTeam("Setter for currentTeam works");
        player2.setPlayerLastName("Setter for lastName works");
        //Sets 2 of the String to "setter works" to make sure the setter actually works.
        
        System.out.println(player2.toString());
        //prints out the values for player2 instance to make sure the changes were made.
        
    }
}
